
/**
 *
 * @author alice
 */
public class GameOptionsPanel extends javax.swing.JPanel
{
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form RegisterFormPanel
     */
    public GameOptionsPanel()
	{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        singlePlayerRadioBtn = new javax.swing.JRadioButton();
        multiplayerRadioBtn = new javax.swing.JRadioButton();
        p1NameLabel = new javax.swing.JLabel();
        p1NameTxtField = new javax.swing.JTextField();
        p1GuestCheckBox = new javax.swing.JCheckBox();
        p2NameLabel = new javax.swing.JLabel();
        p2NameTxtField = new javax.swing.JTextField();
        p2GuestCheckBox = new javax.swing.JCheckBox();
        firstPlayerLabel = new javax.swing.JLabel();
        p1RadioButton = new javax.swing.JRadioButton();
        p2RadioButton = new javax.swing.JRadioButton();
        playButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titleLabel.setText("Game Options");

        buttonGroup1.add(singlePlayerRadioBtn);
        singlePlayerRadioBtn.setText("Single Player");
        singlePlayerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(multiplayerRadioBtn);
        multiplayerRadioBtn.setText("Multiplayer");

        p1NameLabel.setText("Player 1 username:");

        p1NameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1NameTxtFieldActionPerformed(evt);
            }
        });

        p1GuestCheckBox.setText("Guest");
        p1GuestCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1GuestCheckBoxActionPerformed(evt);
            }
        });

        p2NameLabel.setText("Player 2 username:");

        p2NameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2NameTxtFieldActionPerformed(evt);
            }
        });

        p2GuestCheckBox.setText("Guest");
        p2GuestCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2GuestCheckBoxActionPerformed(evt);
            }
        });

        firstPlayerLabel.setText("First player:");

        p1RadioButton.setText("Player 1");
        p1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1RadioButtonActionPerformed(evt);
            }
        });

        p2RadioButton.setText("Player 2");

        playButton.setText("Play Game");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(singlePlayerRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(multiplayerRadioBtn)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(playButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1NameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(p1GuestCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstPlayerLabel)
                                    .addComponent(p2NameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(p2GuestCheckBox))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1RadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p2RadioButton)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singlePlayerRadioBtn)
                    .addComponent(multiplayerRadioBtn))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1NameLabel)
                    .addComponent(p1GuestCheckBox))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2NameLabel)
                            .addComponent(p1NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(p2GuestCheckBox)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2RadioButton)
                    .addComponent(firstPlayerLabel)
                    .addComponent(p1RadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(playButton)
                        .addGap(19, 19, 19)
                        .addComponent(returnButton))
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void singlePlayerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_singlePlayerRadioBtnActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void p1NameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1NameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1NameTxtFieldActionPerformed

    private void p1GuestCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1GuestCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1GuestCheckBoxActionPerformed

    private void p2NameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2NameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2NameTxtFieldActionPerformed

    private void p2GuestCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2GuestCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2GuestCheckBoxActionPerformed

    private void p1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1RadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel firstPlayerLabel;
    private javax.swing.JRadioButton multiplayerRadioBtn;
    private javax.swing.JCheckBox p1GuestCheckBox;
    private javax.swing.JLabel p1NameLabel;
    private javax.swing.JTextField p1NameTxtField;
    private javax.swing.JRadioButton p1RadioButton;
    private javax.swing.JCheckBox p2GuestCheckBox;
    private javax.swing.JLabel p2NameLabel;
    private javax.swing.JTextField p2NameTxtField;
    private javax.swing.JRadioButton p2RadioButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JRadioButton singlePlayerRadioBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    

}
