
import java.awt.CardLayout;


/**
 *
 * @author alice
 */
public class GameOptionsPanel extends UIPanel
{
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form RegisterFormPanel
     */
    public GameOptionsPanel()
	{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        singlePlayerRadioBtn = new javax.swing.JRadioButton();
        multiplayerRadioBtn = new javax.swing.JRadioButton();
        returnButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        singlePlayer = new SuperTicTacToe.src.SinglePlayer();
        multiplayer = new SuperTicTacToe.src.Multiplayer();

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titleLabel.setText("Game Options");

        buttonGroup1.add(singlePlayerRadioBtn);
        singlePlayerRadioBtn.setText("Single Player");
        singlePlayerRadioBtn.setSelected(true);
        singlePlayerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedSinglePlayer(evt);
            }
        });

        buttonGroup1.add(multiplayerRadioBtn);
        multiplayerRadioBtn.setText("Multiplayer");
        multiplayerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedMultiplayer(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        displayPanel.setLayout(new java.awt.CardLayout());
        displayPanel.add(singlePlayer, "first");
        displayPanel.add(multiplayer, "second");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(returnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(singlePlayerRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(multiplayerRadioBtn)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singlePlayerRadioBtn)
                    .addComponent(multiplayerRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        UIWindow.getInstance().close();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void selectedSinglePlayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedSinglePlayer
        // TODO add your handling code here:
        CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "first");
    }//GEN-LAST:event_selectedSinglePlayer

    private void selectedMultiplayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedMultiplayer
        // TODO add your handling code here:
        CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "second");
    }//GEN-LAST:event_selectedMultiplayer


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton exitButton;
    private SuperTicTacToe.src.Multiplayer multiplayer;
    private javax.swing.JRadioButton multiplayerRadioBtn;
    private javax.swing.JButton returnButton;
    private SuperTicTacToe.src.SinglePlayer singlePlayer;
    private javax.swing.JRadioButton singlePlayerRadioBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    

}
