
import javax.swing.JOptionPane;

/**
 *
 * @author Eloy
 */
public class SinglePlayer extends UIPanel {
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form SinglePlayer
     */
    public SinglePlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        aiDifficulty = new javax.swing.ButtonGroup();
        firstPlayer = new javax.swing.ButtonGroup();
        p2NameLabel = new javax.swing.JLabel();
        firstPlayerLabel = new javax.swing.JLabel();
        p1GuestCheckBox = new javax.swing.JCheckBox();
        p1RadioButton = new javax.swing.JRadioButton();
        p2RadioButton = new javax.swing.JRadioButton();
        playButton = new javax.swing.JButton();
        easyButton = new javax.swing.JRadioButton();
        mediumButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        p1NameLabel = new javax.swing.JLabel();
        p1NameTxtField = new javax.swing.JTextField();

        p2NameLabel.setText("Difficulty: ");

        firstPlayerLabel.setText("First player:");

        p1GuestCheckBox.setText("Guest");
        p1GuestCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                p1GuestCheckBoxActionPerformed(evt);
            }
        });

        firstPlayer.add(p1RadioButton);
        p1RadioButton.setSelected(true);
        p1RadioButton.setText("Player 1");
        p1RadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                p1RadioButtonActionPerformed(evt);
            }
        });

        firstPlayer.add(p2RadioButton);
        p2RadioButton.setText("AI");

        playButton.setText("Play Game");
        playButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playButtonActionPerformed(evt);
            }
        });

        aiDifficulty.add(easyButton);
        easyButton.setSelected(true);
        easyButton.setText("Easy");
        easyButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                easyButtonActionPerformed(evt);
            }
        });

        aiDifficulty.add(mediumButton);
        mediumButton.setText("Medium");

        aiDifficulty.add(hardButton);
        hardButton.setText("Hard");

        p1NameLabel.setText("Player 1 username:");

        p1NameTxtField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                p1NameTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1NameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(p1NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p1GuestCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstPlayerLabel)
                            .addComponent(p2NameLabel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(p2RadioButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(easyButton)
                                .addGap(18, 18, 18)
                                .addComponent(mediumButton)
                                .addGap(20, 20, 20)
                                .addComponent(hardButton)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1NameLabel)
                    .addComponent(p1NameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1GuestCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2NameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mediumButton)
                        .addComponent(easyButton)
                        .addComponent(hardButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstPlayerLabel)
                    .addComponent(p1RadioButton)
                    .addComponent(p2RadioButton))
                .addGap(12, 12, 12)
                .addComponent(playButton)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p1GuestCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1GuestCheckBoxActionPerformed
        // TODO add your hasndling code here:
        //p1NameTxtField =
        p1NameTxtField.setEditable(!p1NameTxtField.isEditable());
        if(!p1NameTxtField.isEditable())
        { p1NameTxtField.setText("Guest");} //reference later
        else
        {p1NameTxtField.setText("");}
    }//GEN-LAST:event_p1GuestCheckBoxActionPerformed

    private void p1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1RadioButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyButtonActionPerformed

    private void p1NameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1NameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1NameTxtFieldActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playButtonActionPerformed
    {//GEN-HEADEREND:event_playButtonActionPerformed
		String p1 = this.p1NameTxtField.getText().trim();
		if(p1.length() <= 0)
		{
			JOptionPane.showMessageDialog(this, "Empty player one username value."
				, "Invalid", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		if(p1.equals(Game.AI_NAME) || (!this.p1GuestCheckBox.isSelected() && p1.equals(Game.GUEST_NAME)))
		{
			JOptionPane.showMessageDialog(this, "Invalid username one due to reserved name."
				, "Invalid", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		if(!this.p1GuestCheckBox.isSelected())
		{
			if(UIWindow.getHistoryInstance().getPlayer(p1) == null)
			{
				JOptionPane.showMessageDialog(this, "Username One does not exist."
				, "Invalid", JOptionPane.ERROR_MESSAGE);
				return;
			}
		}
		
		SkillLevel level;
		if(this.easyButton.isSelected())
		{
			level = SkillLevel.Easy;
		}
		else if(this.mediumButton.isSelected())
		{
			level = SkillLevel.Medium;
		}
		else
		{
			level = SkillLevel.Hard;
		}
		
		UIWindow.getInstance().setCurrentPanel(new GridPanel(p1, level, this.p1RadioButton.isSelected()));
    }//GEN-LAST:event_playButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aiDifficulty;
    private javax.swing.JRadioButton easyButton;
    private javax.swing.ButtonGroup firstPlayer;
    private javax.swing.JLabel firstPlayerLabel;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JCheckBox p1GuestCheckBox;
    private javax.swing.JLabel p1NameLabel;
    private javax.swing.JTextField p1NameTxtField;
    private javax.swing.JRadioButton p1RadioButton;
    private javax.swing.JLabel p2NameLabel;
    private javax.swing.JRadioButton p2RadioButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
